### ISSUE TITLE
Mention driver in Centrifugo docs

### ISSUE THREAD

**Issue by FZambia** [AlexHnydiuk/laracent#1]
Hello @AlexHnydiuk  

Just found your driver - looks good! I am going to mention it in Centrifugo documentation - but just wanted to ask your permission and about status of this lib - have you already used it in real project?

**Comment by AlexHnydiuk** [comment]
Hi @FZambia 

Of course you could mention it in Centrifugo docs. But I wanna check it on last laravel version before this.

Answering your question - yes, I'm using it in my pet-project, based on laravel (actually, I've updated old version of the driver, which I mentioned in README.md, specially for my pet-project). And it works just fine. Only after that I decided to post it here.

If you really interested - just drop me a line, and I'll give you link and credentials (my pet-project is still not finished, therefore it can be accesed only with login and pass)

**Comment by FZambia** [comment]
> But I wanna check it on last laravel version before this.

OK, just let me know here.

> I'll give you link and credentials

If it's not very difficult to you then yeah - I am curious to look at, especially on real-time part :) You can send me over email (available on my profile page).

**Comment by AlexHnydiuk** [comment]
Hello again, @FZambia 
Sorry for such a delay, but only today I had enough time to check compability of **laracent** with new version of **laravel**.
I've checked it both with laravel 5.7 and 5.8  using php 7.2 and 7.3 - all green. So you could mention it  Centrifugo documentation, if you wish 😃 
And I discovered, that previosly for tests laravel 5.5 was used 😄  Unexpected backwards compability :gift:
Now minimum version of laravel 5.7 clearly specified in composer.json

**Comment by FZambia** [comment]
Hi, great, thanks! Just added link to https://centrifugal.github.io/centrifugo/libraries/api/ page. Centrifugo is quite popular in Laravel community as far as I know so having a working integration for Centrifugo v2 is pretty cool.
